### ISSUE TITLE
hot reload runner

### ISSUE THREAD

**Issue by gedw99** [Depado/pb-templ-htmx-tailwind#4]
I was trying this out and saw that you were trying to optimise hit reload

https://github.com/cirello-io/runner might be better for controlling the processes. It's pretty amazing what it can do with running many processes and watching for file changes.

works on windows, Mac and linux too.

**Comment by Depado** [comment]
Hi!
Just a warning, this is a work in progress and I'm committing daily to it lately so expect things to break every once in a while!

Thanks for the suggestion! But it seems that wouldn't fit the use case I'm facing here because I need to react differently if different files are changed (recompile when go files change, re-run templ generate when templ file change).
The current implementation "works" but doesn't benefit from hot reloading from templ. 
I'll wait for bokwoon95/wgo#8 to be resolved once (if) a-h/templ#687 is merged :smile:  and then use 

```
templ generate --watch --cmd "wgo ..." 
```

I appreciate the suggestion though!
So it can benefit from both wgo's live reload capabilities and templ's proxy

**Comment by gedw99** [comment]
Yes I know its all alpha and chasing fast but I think its a really good base, and wanted to help out.

no worries - I figure it might be useful but guess not.

I use it to run many processes. It has supervisions trees, so pretty slick.
